Repository not-byte/basketball-form, pull requests merged in 2025-05, with the labels that each got.

#48 docs: changed name in readme.md
  README.md
Labels: documentation

#49 refactor: Changed blood color name to crimson
  src/components/Button/Base.vue
  src/components/Form/Sent.vue
  src/components/Form/Start.vue
  src/components/Form/Summary.vue
  src/components/Input/Base.vue
  src/components/Input/Number.vue
  tailwind.config.ts
Labels: refactor

#50 feat: made about page
  i18n/locale.d.ts
  i18n/locales/pl-PL.ts
  nuxt.config.ts
  package-lock.json
  src/app.vue
  src/assets/css/tailwind.css
  src/components/Button/Link.vue
  src/components/Form/Controls.vue
  src/components/Form/Players.vue
  src/components/Form/Sent.vue
  src/components/Form/Start.vue
  src/components/Form/Summary.vue
  src/components/Form/Team.vue
  src/components/Icon/Logo.vue
  src/components/Input/Base.vue
  src/components/Input/Number.vue
  src/components/Section/About.vue
  src/components/text/Important.vue
  src/components/text/Link.vue
  src/composables/useSiteData.ts
  src/composables/useStageManager.ts
  src/error.vue
  src/pages/about.vue
  src/pages/admin.vue
  src/pages/index.vue
  src/pages/regulations.vue
  src/server/api/form.get.ts
  src/server/api/form.post.ts
  src/types/index.d.ts
  src/utils/getInputType.ts
  src/utils/validateData.ts
  tailwind.config.ts
Labels: feature

#56 feat/internal-api
  .github/workflows/publish.yml
  i18n/locales/pl-PL.ts
  nuxt.config.ts
  package-lock.json
  package.json
  src/components/Form/Controls.vue
  src/components/Form/Players.vue
  src/components/Form/Start.vue
  src/components/Form/Summary.vue
  src/components/Form/Team.vue
  src/components/Input/Base.vue
  src/components/Section/About.vue
  src/components/Select/Category.vue
  src/composables/useSiteData.ts
  src/composables/useStageManager.ts
  src/middleware/auth.ts
  src/pages/about.vue
  src/pages/admin.vue
  src/pages/regulations.vue
  src/public/files/regulations.pdf
  src/server/api/form.get.ts
  src/server/api/form.post.ts
  src/server/utils/useDatabase.ts
  src/types/index.d.ts
Labels: feature

#60 fix: fixed wrong translation keys
  src/components/Form/Sent.vue
  src/components/Form/Summary.vue
Labels: bug
